[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "titan-cli"
version = "1.0.0"
description = "Institutional Trading Intelligence System"
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "Eshu" }
]

dependencies = [
    "typer>=0.16.0",
    "rich>=14.0.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "loguru>=0.7.0"
]

[project.scripts]
titan = "titan.cli:app"

[tool.setuptools]
packages = ["titan"]