"""TUI widgets package."""

from __future__ import annotations

# ─── Semantic CSS class → Rich markup color ──────────────────────

_MARKUP_COLORS: dict[str, str] = {
    "value-active": "green",
    "value-connected": "green",
    "value-healthy": "green",
    "value-positive": "green",
    "value-resolved": "green",
    "value-running": "green",
    "value-success": "green",
    "value-valid": "green",
    "value-buy": "green",
    "audit-success": "green",
    "cb-closed": "green",
    "dec-buy": "green",
    "decision-buy": "green",
    "history-resolved": "green",
    "recovery-success": "green",
    "value-critical": "red",
    "value-disconnected": "red",
    "value-error": "red",
    "value-failed": "red",
    "value-invalid": "red",
    "value-negative": "red",
    "value-sell": "red",
    "value-stopped": "red",
    "value-unhealthy": "red",
    "alert-critical": "red",
    "alert-error": "red",
    "audit-error": "red",
    "cb-open": "red",
    "decision-sell": "red",
    "dec-sell": "red",
    "event-error": "red",
    "log-critical": "red",
    "log-error": "red",
    "reason-critical": "red",
    "recovery-failed": "red",
    "value-degraded": "yellow",
    "value-inactive": "yellow",
    "value-offline": "yellow",
    "value-paused": "yellow",
    "value-warning": "yellow",
    "value-warnings": "yellow",
    "alert-warning": "yellow",
    "audit-warning": "yellow",
    "cb-half-open": "yellow",
    "event-warning": "yellow",
    "history-acknowledged": "yellow",
    "log-warning": "yellow",
    "reason-warning": "yellow",
    "recovery-pending": "yellow",
    "default-class": "dim",
    "dec-none": "dim",
    "decision-none": "dim",
    "value-default": "dim",
    "value-idle": "dim",
    "value-neutral": "dim",
    "value-unknown": "dim",
    "log-debug": "dim",
    "recovery-idle": "dim",
    "alert-info": "cyan",
    "audit-info": "cyan",
    "event-info": "cyan",
    "history-new": "cyan",
    "log-info": "cyan",
    "reason-info": "cyan",
}


def markup_color(css_class: str) -> str:
    """Map a semantic CSS class name to a Rich markup color."""
    return _MARKUP_COLORS.get(css_class, "dim")
