from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from titan.market.series import MarketDataSeries


class SignalType(str, Enum):
    """Types of trading signals generated by a strategy."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


@dataclass(frozen=True, slots=True)
class TradeSignal:
    """A structured trade signal generated by a strategy."""
    signal: SignalType
    symbol: str
    price: float
    stop_loss: float | None = None
    take_profit: float | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


class Strategy(ABC):
    """Abstract base class for trading strategies."""

    @abstractmethod
    def generate_signal(self, data: MarketDataSeries) -> TradeSignal:
        """Analyze market data and generate a trade signal."""
